In [1]:
#Pipeline sequentially apply a list of transforms and a final estimator.

In [2]:
from sklearn.pipeline import Pipeline

#feature scaling

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [3]:
#define steps
steps=[("standard_scalar",StandardScaler()),
       ("classifier", LogisticRegression())]

In [4]:
steps

[('standard_scalar', StandardScaler()), ('classifier', LogisticRegression())]

In [6]:
pipe=Pipeline(steps=steps)

In [7]:
#we have technique to visualize the pipeline in efficient way.
from sklearn import set_config
set_config(display='diagram')

In [8]:
pipe

Pipeline(steps=[('standard_scalar', StandardScaler()),
                ('classifier', LogisticRegression())])

In [9]:
#creating a dataset
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000)

In [10]:
X.shape

(1000, 20)

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(
    X, y,
    test_size=0.33, random_state=42
)

In [12]:
X_train

array([[-1.51702976,  1.44001715,  1.71024189, ..., -0.95332388,
        -0.50438354, -0.63105049],
       [-1.43542897,  0.05113501, -0.16646989, ...,  1.75382122,
         0.62456081,  0.74094482],
       [-1.44766232, -0.42745126, -2.36274736, ..., -0.90803525,
        -1.3020905 ,  0.60953692],
       ...,
       [ 0.65261834,  0.06024862,  0.39766936, ..., -0.99235204,
         0.06736788,  2.7057216 ],
       [-1.40338654,  1.35159108,  1.47533376, ..., -1.18603206,
         1.53286522, -0.76624222],
       [ 0.48185473,  1.49632013, -0.57236261, ...,  0.2014646 ,
        -1.20016085,  0.57087969]])

In [13]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('standard_scalar', StandardScaler()),
                ('classifier', LogisticRegression())])

In [14]:
y_pred=pipe.predict(X_test)

In [15]:
y_pred

array([1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,

In [16]:
#Example3
from sklearn.decomposition import PCA
from sklearn.svm import SVC



In [17]:
steps=[
    ("standard_scalar", StandardScaler()),
    ("pca", PCA(n_components=3)),
    ("svc", SVC())
]

In [19]:
pipe2=Pipeline(steps)

In [20]:
pipe2.fit(X_train,y_train)


Pipeline(steps=[('standard_scalar', StandardScaler()),
                ('pca', PCA(n_components=3)), ('svc', SVC())])

In [21]:
pipe2.predict(X_test)

array([1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,

In [23]:
#complex example of columns transformers
from sklearn.impute import SimpleImputer
import numpy as np


In [24]:
numeric_processor= Pipeline(
    steps=[
        ("impute_mean", SimpleImputer(missing_values=np.nan,strategy='mean' )),
        ('scalar', StandardScaler())
    ]
)

In [25]:
numeric_processor

Pipeline(steps=[('impute_mean', SimpleImputer()), ('scalar', StandardScaler())])

In [26]:
#categorical processing pipeline

from sklearn.preprocessing import OneHotEncoder
category_processor= Pipeline(
    steps=[
        ("impute_constant", SimpleImputer(fill_value="missing", strategy="constant" )),
        ('ohe', OneHotEncoder(handle_unknown="ignore"))
    ]
)

In [27]:
category_processor

Pipeline(steps=[('impute_constant',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('ohe', OneHotEncoder(handle_unknown='ignore'))])

In [30]:
#combine both pipeline
from sklearn.compose import ColumnTransformer

In [31]:
preprocessor=ColumnTransformer(
    [
        ("categorical", category_processor, ["gender", "city"]),
        ("numerical", numeric_processor, ["age", "height"])
    ]
)

In [32]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('impute_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('ohe',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'city']),
                                ('numerical',
                                 Pipeline(steps=[('impute_mean',
                                                  SimpleImputer()),
                                                 ('scalar', StandardScaler())]),
                                 ['age', 'height'])])

In [33]:
from sklearn.pipeline import make_pipeline
model_pipe=make_pipeline(preprocessor, LogisticRegression())

In [34]:
model_pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('impute_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('ohe',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'city']),
                                                 ('numerical',
                                                  Pipeline(steps=[('impute_mean',
                                                                   SimpleImputer()),
                                                                  ('scalar',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])